# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui_display_options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DisplayOptionsDialog(object):
    def setupUi(self, DisplayOptionsDialog):
        DisplayOptionsDialog.setObjectName("DisplayOptionsDialog")
        DisplayOptionsDialog.resize(429, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(DisplayOptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(DisplayOptionsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.colourmapTab = QtWidgets.QWidget()
        self.colourmapTab.setObjectName("colourmapTab")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.colourmapTab)
        self.verticalLayout1.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.colourmapListWidget = QtWidgets.QListWidget(self.colourmapTab)
        self.colourmapListWidget.setObjectName("colourmapListWidget")
        self.verticalLayout1.addWidget(self.colourmapListWidget)
        self.reverseCheckBox = QtWidgets.QCheckBox(self.colourmapTab)
        self.reverseCheckBox.setObjectName("reverseCheckBox")
        self.verticalLayout1.addWidget(self.reverseCheckBox)
        self.tabWidget.addTab(self.colourmapTab, "")
        self.labelsAndScaleTab = QtWidgets.QWidget()
        self.labelsAndScaleTab.setObjectName("labelsAndScaleTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.labelsAndScaleTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showTicksAndLabelsCheckBox = QtWidgets.QCheckBox(self.labelsAndScaleTab)
        self.showTicksAndLabelsCheckBox.setObjectName("showTicksAndLabelsCheckBox")
        self.verticalLayout_2.addWidget(self.showTicksAndLabelsCheckBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.labelsAndScaleTab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.overallTitleLineEdit = QtWidgets.QLineEdit(self.labelsAndScaleTab)
        self.overallTitleLineEdit.setObjectName("overallTitleLineEdit")
        self.horizontalLayout_2.addWidget(self.overallTitleLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.showProjectFilenameCheckBox = QtWidgets.QCheckBox(self.labelsAndScaleTab)
        self.showProjectFilenameCheckBox.setObjectName("showProjectFilenameCheckBox")
        self.verticalLayout_2.addWidget(self.showProjectFilenameCheckBox)
        self.showDateCheckBox = QtWidgets.QCheckBox(self.labelsAndScaleTab)
        self.showDateCheckBox.setObjectName("showDateCheckBox")
        self.verticalLayout_2.addWidget(self.showDateCheckBox)
        self.line = QtWidgets.QFrame(self.labelsAndScaleTab)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.useScaleCheckBox = QtWidgets.QCheckBox(self.labelsAndScaleTab)
        self.useScaleCheckBox.setObjectName("useScaleCheckBox")
        self.verticalLayout_2.addWidget(self.useScaleCheckBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pixelSizeLabel = QtWidgets.QLabel(self.labelsAndScaleTab)
        self.pixelSizeLabel.setObjectName("pixelSizeLabel")
        self.horizontalLayout.addWidget(self.pixelSizeLabel)
        self.pixelSizeLineEdit = QtWidgets.QLineEdit(self.labelsAndScaleTab)
        self.pixelSizeLineEdit.setObjectName("pixelSizeLineEdit")
        self.horizontalLayout.addWidget(self.pixelSizeLineEdit)
        self.unitsComboBox = QtWidgets.QComboBox(self.labelsAndScaleTab)
        self.unitsComboBox.setObjectName("unitsComboBox")
        self.horizontalLayout.addWidget(self.unitsComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.showScaleBarCheckBox = QtWidgets.QCheckBox(self.labelsAndScaleTab)
        self.showScaleBarCheckBox.setObjectName("showScaleBarCheckBox")
        self.verticalLayout_2.addWidget(self.showScaleBarCheckBox)
        self.scaleBarLocationGroupBox = QtWidgets.QGroupBox(self.labelsAndScaleTab)
        self.scaleBarLocationGroupBox.setObjectName("scaleBarLocationGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.scaleBarLocationGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.upperLeftRadioButton = QtWidgets.QRadioButton(self.scaleBarLocationGroupBox)
        self.upperLeftRadioButton.setObjectName("upperLeftRadioButton")
        self.gridLayout.addWidget(self.upperLeftRadioButton, 0, 0, 1, 1)
        self.upperRightRadioButton = QtWidgets.QRadioButton(self.scaleBarLocationGroupBox)
        self.upperRightRadioButton.setObjectName("upperRightRadioButton")
        self.gridLayout.addWidget(self.upperRightRadioButton, 0, 1, 1, 1)
        self.lowerLeftRadioButton = QtWidgets.QRadioButton(self.scaleBarLocationGroupBox)
        self.lowerLeftRadioButton.setObjectName("lowerLeftRadioButton")
        self.gridLayout.addWidget(self.lowerLeftRadioButton, 1, 0, 1, 1)
        self.lowerRightRadioButton = QtWidgets.QRadioButton(self.scaleBarLocationGroupBox)
        self.lowerRightRadioButton.setObjectName("lowerRightRadioButton")
        self.gridLayout.addWidget(self.lowerRightRadioButton, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.scaleBarLocationGroupBox)
        self.scaleBarColourGroupBox = QtWidgets.QGroupBox(self.labelsAndScaleTab)
        self.scaleBarColourGroupBox.setObjectName("scaleBarColourGroupBox")
        self.scaleBarColourLayout = QtWidgets.QVBoxLayout(self.scaleBarColourGroupBox)
        self.scaleBarColourLayout.setObjectName("scaleBarColourLayout")
        self.blackRadioButton = QtWidgets.QRadioButton(self.scaleBarColourGroupBox)
        self.blackRadioButton.setObjectName("blackRadioButton")
        self.scaleBarColourLayout.addWidget(self.blackRadioButton)
        self.whiteRadioButton = QtWidgets.QRadioButton(self.scaleBarColourGroupBox)
        self.whiteRadioButton.setObjectName("whiteRadioButton")
        self.scaleBarColourLayout.addWidget(self.whiteRadioButton)
        self.verticalLayout_2.addWidget(self.scaleBarColourGroupBox)
        self.dummyLabel = QtWidgets.QLabel(self.labelsAndScaleTab)
        self.dummyLabel.setText("")
        self.dummyLabel.setObjectName("dummyLabel")
        self.verticalLayout_2.addWidget(self.dummyLabel)
        self.tabWidget.addTab(self.labelsAndScaleTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(DisplayOptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DisplayOptionsDialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(DisplayOptionsDialog.accept)
        self.buttonBox.rejected.connect(DisplayOptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DisplayOptionsDialog)

    def retranslateUi(self, DisplayOptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        DisplayOptionsDialog.setWindowTitle(_translate("DisplayOptionsDialog", "Display Options"))
        self.reverseCheckBox.setText(_translate("DisplayOptionsDialog", "Reverse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colourmapTab), _translate("DisplayOptionsDialog", "Colourmap"))
        self.showTicksAndLabelsCheckBox.setText(_translate("DisplayOptionsDialog", "Show axes ticks and labels"))
        self.label.setText(_translate("DisplayOptionsDialog", "Title"))
        self.showProjectFilenameCheckBox.setText(_translate("DisplayOptionsDialog", "Show project filename (bottom left)"))
        self.showDateCheckBox.setText(_translate("DisplayOptionsDialog", "Show date (bottom right)"))
        self.useScaleCheckBox.setText(_translate("DisplayOptionsDialog", "Use physical scale"))
        self.pixelSizeLabel.setText(_translate("DisplayOptionsDialog", "Pixel size"))
        self.showScaleBarCheckBox.setText(_translate("DisplayOptionsDialog", "Show scale bar"))
        self.scaleBarLocationGroupBox.setTitle(_translate("DisplayOptionsDialog", "Scale bar location"))
        self.upperLeftRadioButton.setText(_translate("DisplayOptionsDialog", "Upper left"))
        self.upperRightRadioButton.setText(_translate("DisplayOptionsDialog", "Upper right"))
        self.lowerLeftRadioButton.setText(_translate("DisplayOptionsDialog", "Lower left"))
        self.lowerRightRadioButton.setText(_translate("DisplayOptionsDialog", "Lower right"))
        self.scaleBarColourGroupBox.setTitle(_translate("DisplayOptionsDialog", "Scale bar colour"))
        self.blackRadioButton.setText(_translate("DisplayOptionsDialog", "Black"))
        self.whiteRadioButton.setText(_translate("DisplayOptionsDialog", "White"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.labelsAndScaleTab), _translate("DisplayOptionsDialog", "Labels and scale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DisplayOptionsDialog = QtWidgets.QDialog()
    ui = Ui_DisplayOptionsDialog()
    ui.setupUi(DisplayOptionsDialog)
    DisplayOptionsDialog.show()
    sys.exit(app.exec_())

