# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui_new_phase_filtered_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewPhaseFilteredDialog(object):
    def setupUi(self, NewPhaseFilteredDialog):
        NewPhaseFilteredDialog.setObjectName("NewPhaseFilteredDialog")
        NewPhaseFilteredDialog.resize(620, 721)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewPhaseFilteredDialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 660, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.elementTable = QtWidgets.QTableWidget(NewPhaseFilteredDialog)
        self.elementTable.setGeometry(QtCore.QRect(40, 30, 431, 111))
        self.elementTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.elementTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.elementTable.setShowGrid(False)
        self.elementTable.setColumnCount(4)
        self.elementTable.setObjectName("elementTable")
        self.elementTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.elementTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.elementTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.elementTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.elementTable.setHorizontalHeaderItem(3, item)
        self.elementTable.horizontalHeader().setHighlightSections(False)
        self.elementTable.horizontalHeader().setStretchLastSection(True)
        self.elementTable.verticalHeader().setVisible(False)
        self.matplotlibWidget = MatplotlibWidget(NewPhaseFilteredDialog)
        self.matplotlibWidget.setGeometry(QtCore.QRect(49, 159, 391, 351))
        self.matplotlibWidget.setObjectName("matplotlibWidget")
        self.lowerSlider = QtWidgets.QSlider(NewPhaseFilteredDialog)
        self.lowerSlider.setGeometry(QtCore.QRect(470, 150, 16, 361))
        self.lowerSlider.setStyleSheet("")
        self.lowerSlider.setSingleStep(10)
        self.lowerSlider.setPageStep(100)
        self.lowerSlider.setOrientation(QtCore.Qt.Vertical)
        self.lowerSlider.setInvertedAppearance(False)
        self.lowerSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.lowerSlider.setTickInterval(100)
        self.lowerSlider.setObjectName("lowerSlider")
        self.upperSlider = QtWidgets.QSlider(NewPhaseFilteredDialog)
        self.upperSlider.setGeometry(QtCore.QRect(520, 150, 16, 361))
        self.upperSlider.setSingleStep(10)
        self.upperSlider.setPageStep(100)
        self.upperSlider.setOrientation(QtCore.Qt.Vertical)
        self.upperSlider.setObjectName("upperSlider")
        self.label = QtWidgets.QLabel(NewPhaseFilteredDialog)
        self.label.setGeometry(QtCore.QRect(460, 510, 48, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NewPhaseFilteredDialog)
        self.label_2.setGeometry(QtCore.QRect(510, 510, 48, 13))
        self.label_2.setObjectName("label_2")
        self.lowerLineEdit = QtWidgets.QLineEdit(NewPhaseFilteredDialog)
        self.lowerLineEdit.setGeometry(QtCore.QRect(420, 530, 81, 21))
        self.lowerLineEdit.setReadOnly(True)
        self.lowerLineEdit.setObjectName("lowerLineEdit")
        self.upperLineEdit = QtWidgets.QLineEdit(NewPhaseFilteredDialog)
        self.upperLineEdit.setGeometry(QtCore.QRect(510, 530, 81, 21))
        self.upperLineEdit.setReadOnly(True)
        self.upperLineEdit.setObjectName("upperLineEdit")
        self.updateThresholdsButton = QtWidgets.QPushButton(NewPhaseFilteredDialog)
        self.updateThresholdsButton.setGeometry(QtCore.QRect(410, 560, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateThresholdsButton.sizePolicy().hasHeightForWidth())
        self.updateThresholdsButton.setSizePolicy(sizePolicy)
        self.updateThresholdsButton.setObjectName("updateThresholdsButton")
        self.label_3 = QtWidgets.QLabel(NewPhaseFilteredDialog)
        self.label_3.setGeometry(QtCore.QRect(330, 560, 71, 17))
        self.label_3.setObjectName("label_3")
        self.clearThresholdsButton = QtWidgets.QPushButton(NewPhaseFilteredDialog)
        self.clearThresholdsButton.setGeometry(QtCore.QRect(500, 560, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearThresholdsButton.sizePolicy().hasHeightForWidth())
        self.clearThresholdsButton.setSizePolicy(sizePolicy)
        self.clearThresholdsButton.setObjectName("clearThresholdsButton")
        self.label_4 = QtWidgets.QLabel(NewPhaseFilteredDialog)
        self.label_4.setGeometry(QtCore.QRect(160, 620, 111, 17))
        self.label_4.setObjectName("label_4")
        self.nameLineEdit = QtWidgets.QLineEdit(NewPhaseFilteredDialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(250, 610, 113, 25))
        self.nameLineEdit.setObjectName("nameLineEdit")

        self.retranslateUi(NewPhaseFilteredDialog)
        self.buttonBox.accepted.connect(NewPhaseFilteredDialog.accept)
        self.buttonBox.rejected.connect(NewPhaseFilteredDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewPhaseFilteredDialog)

    def retranslateUi(self, NewPhaseFilteredDialog):
        _translate = QtCore.QCoreApplication.translate
        NewPhaseFilteredDialog.setWindowTitle(_translate("NewPhaseFilteredDialog", "New phase map from filtered element maps"))
        self.elementTable.setSortingEnabled(True)
        item = self.elementTable.horizontalHeaderItem(0)
        item.setText(_translate("NewPhaseFilteredDialog", "Symbol"))
        item = self.elementTable.horizontalHeaderItem(1)
        item.setText(_translate("NewPhaseFilteredDialog", "Name"))
        item = self.elementTable.horizontalHeaderItem(2)
        item.setText(_translate("NewPhaseFilteredDialog", "Lower"))
        item = self.elementTable.horizontalHeaderItem(3)
        item.setText(_translate("NewPhaseFilteredDialog", "Upper"))
        self.label.setText(_translate("NewPhaseFilteredDialog", "Lower"))
        self.label_2.setText(_translate("NewPhaseFilteredDialog", "Upper"))
        self.updateThresholdsButton.setText(_translate("NewPhaseFilteredDialog", "Update"))
        self.label_3.setText(_translate("NewPhaseFilteredDialog", "Thresholds"))
        self.clearThresholdsButton.setText(_translate("NewPhaseFilteredDialog", "Clear"))
        self.label_4.setText(_translate("NewPhaseFilteredDialog", "Phase name"))

from .matplotlib_widget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewPhaseFilteredDialog = QtWidgets.QDialog()
    ui = Ui_NewPhaseFilteredDialog()
    ui.setupUi(NewPhaseFilteredDialog)
    NewPhaseFilteredDialog.show()
    sys.exit(app.exec_())

