# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui_new_phase_cluster_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewPhaseClusterDialog(object):
    def setupUi(self, NewPhaseClusterDialog):
        NewPhaseClusterDialog.setObjectName("NewPhaseClusterDialog")
        NewPhaseClusterDialog.resize(686, 733)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewPhaseClusterDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.matplotlibWidget = MatplotlibWidget(NewPhaseClusterDialog)
        self.matplotlibWidget.setObjectName("matplotlibWidget")
        self.verticalLayout_2.addWidget(self.matplotlibWidget)
        self.statusLabel = QtWidgets.QLabel(NewPhaseClusterDialog)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(NewPhaseClusterDialog)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(NewPhaseClusterDialog)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(NewPhaseClusterDialog)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.clearButton = QtWidgets.QPushButton(NewPhaseClusterDialog)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout.addWidget(self.clearButton)
        self.deleteButton = QtWidgets.QPushButton(NewPhaseClusterDialog)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        self.mergeButton = QtWidgets.QPushButton(NewPhaseClusterDialog)
        self.mergeButton.setObjectName("mergeButton")
        self.verticalLayout.addWidget(self.mergeButton)
        self.label_2 = QtWidgets.QLabel(NewPhaseClusterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewPhaseClusterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(3, 1)

        self.retranslateUi(NewPhaseClusterDialog)
        self.buttonBox.accepted.connect(NewPhaseClusterDialog.accept)
        self.buttonBox.rejected.connect(NewPhaseClusterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewPhaseClusterDialog)

    def retranslateUi(self, NewPhaseClusterDialog):
        _translate = QtCore.QCoreApplication.translate
        NewPhaseClusterDialog.setWindowTitle(_translate("NewPhaseClusterDialog", "Create new phase maps from cluster map"))
        self.statusLabel.setText(_translate("NewPhaseClusterDialog", "status"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("NewPhaseClusterDialog", "Phase name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("NewPhaseClusterDialog", "Value"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("NewPhaseClusterDialog", "Colour"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("NewPhaseClusterDialog", "Pixels"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("NewPhaseClusterDialog", "Original values"))
        self.label.setText(_translate("NewPhaseClusterDialog", "Select phases to delete/merge."))
        self.label_3.setText(_translate("NewPhaseClusterDialog", "Double-click on a phase name to change it."))
        self.clearButton.setText(_translate("NewPhaseClusterDialog", "Clear selections"))
        self.deleteButton.setText(_translate("NewPhaseClusterDialog", "Delete selected phases"))
        self.mergeButton.setText(_translate("NewPhaseClusterDialog", "Merge selected phases"))

from .matplotlib_widget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewPhaseClusterDialog = QtWidgets.QDialog()
    ui = Ui_NewPhaseClusterDialog()
    ui.setupUi(NewPhaseClusterDialog)
    NewPhaseClusterDialog.show()
    sys.exit(app.exec_())

