import sys
import os
def equations(choice):
    corr_dic = {"General":{"Na":{"model":"poly","order":2,"int":0,"a":,"b":},
                           "Mg":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                           "Al":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                           "Si":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "K":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Ca":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                           "Ti":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                           "Cr":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Mn":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                           "Fe":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Ni":{"model":"poly","order":2,"int":0,"a":,"b":},
                           "MgN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "CrN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "An":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "Or":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "Py":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "Gro":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "Alm":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Sp":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":}},
                "Feldspar":{"Na":{"model":"poly","order":2,"int":0,"a":,"b":},
                            "Mg":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Al":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Si":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "K":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Ca":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Ti":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Cr":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                            "Mn":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Fe":{"model":"poly","order":2,"int":0,"a":,"b":},
                            "Ni":{"model":"poly","order":2,"int":0,"a":,"b":},
                            "An":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                            "Or":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":}},
                "Garnet":{"Na":{"model":"poly","order":2,"int":0,"a":,"b":},
                          "Mg":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                          "Al":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                          "Si":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                          "K":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                          "Ca":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                          "Ti":{"model":"poly","order":2,"int":0,"a":,"b":},
                          "Cr":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                          "Mn":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                          "Fe":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                          "Ni":{"model":"poly","order":2,"int":0,"a":,"b":},
                          "MgN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                          "CrN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                          "Py":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                          "Gro":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                          "Alm":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                          "Sp":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":}},
                
                "Olivine":{"Na":{"model":"poly","order":2,"int":0,"a":,"b":},
                           "Mg":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                           "Al":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                           "Si":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                           "K":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Ca":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                           "Ti":{"model":"poly","order":2,"int":0,"a":,"b":},
                           "Cr":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Mn":{"model":"poly","order":3,"int":0,"a":,"b":,"c":,"d":},
                           "Fe":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                           "Ni":{"model":"poly","order":2,"int":0,"a":,"b":},
                           "MgN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                           "CrN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":}},
                
                "Oxide":{"Na":{"model":"poly","order":2,"int":0,"a":,"b":},
                         "Mg":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                         "Al":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                         "Si":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                         "K":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                         "Ca":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                         "Ti":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                         "Cr":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                         "Mn":{"model":"poly","order":3,"int":0,"a":,"b":,"c":,},
                         "Fe":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                         "Ni":{"model":"poly","order":2,"int":0,"a":,"b":},
                         "MgN":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                         "CrN":{"model":"poly","order":3,"int":0,"a":,"b":,"c":}},
                
                "Pyroxene":{"Na":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Mg":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Al":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Si":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "K":{"model":"poly","order":5,"int":0,"a":,"b":,"c":,"d":,"e":},
                            "Ca":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Ti":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Cr":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Mn":{"model":"poly","order":3,"int":0,"a":,"b":,"c":},
                            "Fe":{"model":"poly","order":4,"int":0,"a":,"b":,"c":,"d":},
                            "Ni":{"model":"poly","order":2,"int":0,"a":,"b":},
                            "MgN":{"model":"poly","order":6,"int":0,"a":,"b":,"c":,"d":,"e":,"f":},
                            "CrN":{"model":"poly","order":3,"int":0,"a":,"b":,"c":}}
                }
    if choice == "General":
        chdic = corr_dic["General"]
    elif choice == "Plagioclase":
        chdic = corr_dic["Plagioclase"]
    elif choice == "Pyroxene":
        chdic = corr_dic["Pyroxene"]
    elif choice == "Olivine":
        chdic = corr_dic["Olivine"]
    del corr_dic
    return chdic
