# Writes element properties to stdout, the same as in elements.py file.

import math
import mendeleev

max_name_length = 12
max_A_length = 14


print('# This file is generated by make_elements.py script')
print('# Properties are name, atomic number, atomic weight, solid density at 295 K (g/cm^3)')
print('element_properties = { \\')
for Z in range(1, 93):
    element = mendeleev.element(Z)

    line = "    '{}'".format(element.symbol)
    if len(element.symbol) < 2:
        line += ' '
    line += ": ('{}',".format(element.name.lower())
    line += ' '*(max_name_length - len(element.name))
    line += ' {:>2}, '.format(element.atomic_number)

    temp = ' '*(2-int(math.log10(element.atomic_weight)))
    temp += '{},'.format(element.atomic_weight)
    temp += ' '*(max_A_length - len(temp))
    line += temp

    if element.melting_point < 295.0 or element.density is None:
        line += " None"
    else:
        line += ' {}'.format(element.density)
    line += '),'

    print(line)
print('}')
